  
name: Test and create report

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.17.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - name: run test
      run: npm run test
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: allure-results-test
        path: ./allure-results
    - name: Create Report
      if: always()
    # trying to save history of previous runs if it is exists
      run: cp -r $(pwd)/docs/history/. $(pwd)/allure-results/history || true && npm run allure:generate
    - name: Deploy report
      uses: JamesIves/github-pages-deploy-action@3.1.0
      if: always()
      with:
        ACCESS_TOKEN: ${{ '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' }}
        BRANCH: master # The branch the action should deploy to.
        FOLDER: allure-report # The folder the action should deploy.
        TARGET_FOLDER: docs
  test1:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.17.0]
        # See supported Node.js release schedule at https://nodejs.org/en/
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - name: run test1
      run: npm run test1
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: allure-results-test1
        path: ./allure-results
    - name: Create Report
      if: always()
    # trying to save history of previous runs if it is exists
      run: cp -r $(pwd)/docs/history/. $(pwd)/allure-results/history || true && npm run allure:generate
#     - name: Upload Artifact
#       uses: actions/upload-artifact@v1
#       if: always()
#       with:
#         name: allure-report
#         path: ./allure-report
  store_results_and_generate_report:
    needs: [test,test1]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.17.0]
        # See supported Node.js release schedule at https://nodejs.org/en/
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
    - name: 'Echo download path'
      run: echo ${{steps.download.outputs.download-path}}
    - name: Display structure of downloaded files
      run: ls -R
    - name: Unpack artifacts
      if: always()
#       run: 7z x allure-results-test ./allure-results && 7z x allure-results-test1 ./allure-results
      run: cp -r allure-results-test/. ./allure-results && cp -r allure-results-test1/. ./allure-results   
    - name: Display structure of downloaded files
      run: ls -R
    - name: Generate allure-report
      if: always()
      run: npm run allure:generate
    - name: Deploy report
      uses: JamesIves/github-pages-deploy-action@3.1.0
      if: always()
      with:
        ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
        BRANCH: master # The branch the action should deploy to.
        FOLDER: allure-report # The folder the action should deploy.
        TARGET_FOLDER: docs
    - name: Pushes docs to another repository
      uses: cpina/github-action-push-to-another-repository@main
      if: always()
      env:
        API_TOKEN_GITHUB: ${{secrets.API_TOKEN_GITHUB}}
      with:
        source-directory: 'docs'
        destination-github-username: 'ToActions'
        destination-repository-name: 'HtmlActions'
        user-email: s.fart2012@gmail.com
        target-branch: main
